# Generated by Django 2.1.7 on 2019-03-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
