# Generated by Django 2.1.7 on 2019-03-30 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20190330_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_time',
            field=models.IntegerField(unique=True),
        ),
    ]
